### ISSUE TITLE
store keys in plaintext?

### ISSUE THREAD

**Issue by gnullByte** [freshprince/weechat-fish#16]
Just a thought, but it doesn't seem like a good idea to implement encryption only to store the key in plaintext. I'm looking into how to add this at the moment, but am unfamiliar with the weechat api. Maybe a few days, anyway if you feel like writing it before then by all means! Otherwise a great plugin, thanks for the hard work.

**Comment by azrdev** [comment]
The go-to solution would be to store them in `/secure` storage, where the user can set a master key if she wishes

**Comment by azrdev** [comment]
apparently this is implemented in v0.9.4 which is available on https://weechat.org/scripts/source/fish.py.html/ but this repo is not updated

**Comment by gnullByte** [comment]
Right, `/secure` hadn't been implemented yet at the time of this issue on this repo. I implemented encrypting the keys manually, and then switched over to `/secure` when it was added. I'm not sure where the more updated repo is now, but my changes are here: https://github.com/gnullByte/weechat-fish/commits/master/fish.py

**Comment by gnullByte** [comment]
This might be it: https://github.com/mawashii/weechat-fish
