### ISSUE TITLE
key length

### ISSUE THREAD

**Issue by c0ffee** [freshprince/weechat-fish#2]
the official fish accepts key length of 72 bytes (576 bit)

pycrypto accepts only keys with a max length of 56 bytes(448 bit) which is the standard for blowcrypt, so you get an error msg

the problem is to fix that you need to use another crypto engine... but without its not compatible to fish and in many cases useless 

i really like your plugin, because i want to move finally from irssi to weechat and hope that it is more stable(fish implementation for irssi is a hell on earth!)

**Comment by f1reflyyyylmao** [comment]
@jra89 Did you get it to work somehow? I'm at the same point as you two years ago...

**Comment by jra89** [comment]
@f1reflyyyylmao I did, but I can't remember what I did unfortunately, nor do I remember where I put the patched code. If I remember correctly I used the above mentioned workaround and then put some file in the same folder as the modified file to tell it where python-crypt was located, but that is more of a hunch than anything. I did get it to work though.

**Comment by bendep** [comment]
are there any news on that topic?
i think, many people are having that problem :(

**Comment by freshprince** [comment]
This should now be fixed with the switch to pycryptodome which as far as I saw has `keylength > 72`. Please let me know if this issue still persists by reopening.
