### ISSUE TITLE
allow disabling encryption

### ISSUE THREAD

**Issue by azrdev** [freshprince/weechat-fish#21]
Like summarized [here](http://blog.sjas.de/posts/weechat-enable-or-disable-fish.html), the only ways to disable encryption are to unload the plugin or remove the key(s) corresponding to a contact.

for debugging (or when people switch clients) it would be useful to disable encryption
1. for a single message (a possibility might be to not encrypt when using `/say` (see also #20), or mirror the mirc behaviour: don't encrypt when the message has prefix `+p`)
2. per contact,  without removing the stored key
3. overall (here plugin unloading might suffice)

**Comment by freshprince** [comment]
won't do
