### ISSUE TITLE
fish.py crashes with python 3.7.0

### ISSUE THREAD

**Issue by dinasty02091994** [freshprince/weechat-fish#22]
whenever i receive an encrypted message the following traceback is displayed in weechat, the message received stays encrypted.
 
python: stdout/stderr (fish): Traceback (most recent call last):
python: stdout/stderr (fish):   File
"/home/user/.weechat/python/autoload/fish.py", line 703, in
fish_modifier_in_privmsg_cb
python: stdout/stderr (fish):     b = Blowfish(fish_keys[targetl])
python: stdout/stderr (fish):   File
"/home/user/.weechat/python/autoload/fish.py", line 235, in __init__      
python: stdout/stderr (fish):     self.blowfish =
Crypto.Cipher.Blowfish.new(key)
python: stdout/stderr (fish): TypeError: new() takes at least 2 arguments (1 given)
python: error in function "fish_modifier_in_privmsg_cb"

**Comment by dr0id123** [comment]
https://github.com/weechat/scripts/issues/384

**Comment by freshprince** [comment]
ported to python3
