### ISSUE TITLE
weechat updated to 2.7.2 -> script fails to load with "Python Cryptography Toolkit must be installed to use fish"

### ISSUE THREAD

**Issue by att2** [freshprince/weechat-fish#24]
Hello,

My CentOS 7 auto-updated WeeChat to 2.7.2 and since then, FISH plugin fails to load with: "Python Cryptography Toolkit must be installed to use fish"

despite everything worked correctly before. Please help. 

Basically I did 

yum install python2-devel
git clone https://github.com/dlitz/pycrypto.git
cd pycrypto
python setup.py build
python setup.py install

and that worked. But now, the weechat update broke something and I don't know what it is.

**Comment by freshprince** [comment]
since version 2.6 weechat uses python 3 as default for plugins maybe you need to install pycrypto for python 3

**Comment by att2** [comment]
You are right, they switched from python2 to python3. So the right way to do it is
yum install python3-devel
and
python3 setup.py build / install
Thanks for the clue, it was not obvious to me.
